name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Elixir ${{ matrix.elixir }}
    runs-on: ubuntu-latest
    container:
      image: elixir:${{ matrix.elixir }}
    strategy:
      fail-fast: false
      matrix:
        elixir:
        - '1.16'
        - '1.15'
        - '1.14'
        - '1.13'
        - '1.12'
        - '1.11'
        - '1.10'
        - '1.9'
        - '1.8'
        - '1.7'
        - '1.6'
        - '1.5'

    steps:
      - uses: actions/checkout@v3

      - name: Setup Environment
        run: |
          epmd -daemon
          mix local.hex --force
          mix local.rebar --force
          mix deps.get

      - name: Run Tests
        run: mix test --trace

  Coverage:
    name: Coverage Reporting
    runs-on: ubuntu-latest
    container:
      image: elixir:1.16
    env:
      MIX_ENV: cover
    steps:
      - uses: actions/checkout@v3

      - name: Setup Environment
        run: |
          epmd -daemon
          mix local.hex --force
          mix local.rebar --force
          mix deps.get

      - name: Generate Coverage
        run: mix coveralls.github
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
